language: node_js

node_js:
  - 'node'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

cache:
  apt: true

before_install:
  # - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  # - sudo apt-get update
  # - sudo apt-get install gcc-6 g++-6 -y
  - ./get-engines.sh

script:
  - yarn test:ci

addons:
  code_climate:
    repo_token: 021623ddc84333ae17afad25ec5391d51b61f7766d58bc3d4e695cb93ac1f2cd

branches:
  except:
    - gh-pages
